spring:
  jpa:
    properties:
      hibernate:
        dialect: io.roach.bank.repository.jpa.CockroachDBDialect
    show-sql: false
    open-in-view: false
  main:
    allow-bean-definition-overriding: true
  flyway:
    connect-retries: 50
    enabled: true
    locations: classpath:db/migration/crdb,classpath:db/migration/common
    clean-on-validation-error: true
#############################
roachbank:
  health:
    validation-query: select node_id from [SHOW CLUSTER SESSIONS] limit 1
  datasource:
    url: jdbc:postgresql://localhost:26257/roach_bank?sslmode=disable&reWriteBatchedInserts=true
    driver-class-name: org.postgresql.Driver
    username: root
    password:
    configuration:
      pool-name: roach-bank
      testOnBorrow: true
      connection-init-sql: SELECT 1
      connection-timeout: 30000
      validation-timeout: 20000
      max-lifetime: 60000
      # 36vcpu x 9 nodes x 4 / 3 instances
      maximum-pool-size: 430
      minimum-idle: 110
