spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: false
    open-in-view: false
  main:
    allow-bean-definition-overriding: true
  liquibase:
    contexts: db-psql
    default-schema: public
    drop-first: false
    enabled: true
    change-log: classpath:db/changelog-master.xml
    database-change-log-table: db_changelog
    database-change-log-lock-table: db_changelog_lock
#############################
roachbank:
  health:
    validation-query: select 1
  datasource:
    url: jdbc:postgresql://localhost:5432/roach_bank
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    hikari:
      register-mbeans: false
      initialization-fail-timeout: 30
      pool-name: roach-bank
      connection-init-sql: SELECT 1
      connection-timeout: 30000
      validation-timeout: 10000
      # 36vcpu x 9 baseline, 1 client
      maximum-pool-size: 1300
      # should be same as maximum-pool-size
      minimum-idle: 1300
      # Required for PSQL
      transaction-isolation: TRANSACTION_SERIALIZABLE
