spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: false
    open-in-view: false
  main:
    allow-bean-definition-overriding: true
  flyway:
    connect-retries: 50
    enabled: true
    locations: classpath:db/migration/psql,classpath:db/migration/common
    clean-on-validation-error: true
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/roach_bank
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    hikari:
      transaction-isolation: TRANSACTION_SERIALIZABLE
      pool-name: roach-bank
      connection-init-sql: SELECT 1
      connection-timeout: 30000
      validation-timeout: 20000
      max-lifetime: 60000
      # 36vcpu x 9 nodes x 4 = 1300 total
      # Per client 36*2 threads ~= 80
      maximum-pool-size: 80
      # max size / 2
      minimum-idle: 40
#############################
roachbank:
  health:
    validation-query: select 1
