roachbank:
  datasource:
    url: jdbc:postgresql://192.168.1.99:26300/roach_bank?sslmode=disable&reWriteBatchedInserts
#    url: jdbc:postgresql://192.168.1.99:5432/roach_bank?reWriteBatchedInserts=true
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    configuration:
      pool-name: roach-bank
      testOnBorrow: true
      connection-init-sql: SELECT 1
      connection-timeout: 30000
      validation-timeout: 20000
      max-lifetime: 60000
      maximum-pool-size: 32
      minimum-idle: 32
