--
-- Metadata used for bank transactions and client account selection
--

-- TRUNCATE TABLE region CASCADE;

INSERT into region
VALUES ('eu-north', 'stockholm,copenhagen,helsinki,oslo,riga,tallinn'),
       ('eu-west', 'dublin,belfast,london,liverpool,manchester,glasgow,birmingham,leeds'),
       ('eu-central', 'amsterdam,rotterdam,antwerp,hague,ghent,brussels,berlin,hamburg,munich,frankfurt,dusseldorf,leipzig,dortmund,essen,stuttgart'),
       ('eu-south', 'madrid,barcelona,sintra,rome,milan,lyon,lisbon,toulouse,paris,cologne,seville,marseille,naples,turin,valencia,palermo'),
       ('eu-east', 'krakov,zagraeb,zaragoza,lodz,athens,bratislava,prague,sofia,bucharest,vienna,warsaw,budapest'),

       ('us-west', 'seattle,san francisco,los angeles,portland,las vegas'),
       ('us-east', 'new york,boston,washington dc,miami,charlotte'),
       ('us-central', 'phoenix,minneapolis,chicago,detroit,atlanta'),

       ('ap-northeast', 'hong kong,beijing,shanghai,tokyo'),
       ('ap-southeast', 'singapore,jakarta,sydney,melbourne'),

       ('sa-east', 'sao paulo,rio de janeiro,salvador,buenos aires');

INSERT into cloud_region
VALUES ('us-east-1', 'us-east'),
       ('us-east-2', 'us-east'),
       ('us-west-1', 'us-west'),
       ('us-west-2', 'us-west'),
       ('ca-central-1', 'us-central'),
       ('eu-central-1', 'eu-central'),
       ('eu-west-1', 'eu-west'),
       ('eu-west-2', 'eu-west'),
       ('eu-west-3', 'eu-south'),
       ('ap-northeast-1', 'ap-northeast'),
       ('ap-northeast-2', 'ap-northeast'),
       ('ap-northeast-3', 'ap-northeast'),
       ('ap-southeast-1', 'ap-southeast'),
       ('ap-southeast-2', 'ap-southeast'),
       ('ap-south-1', 'ap-southeast'),
       ('sa-east-1', 'sa-east'),
       ('eastasia', 'ap-northeast'),
       ('southeastasia', 'ap-southeast'),
       ('centralus', 'us-central'),
       ('eastus', 'us-east'),
       ('eastus2', 'us-east'),
       ('westus', 'us-west'),
       ('northcentralus', 'us-central'),
       ('southcentralus', 'us-central'),
       ('northeurope', 'eu-north'),
       ('westeurope', 'eu-north'),
       ('japanwest', 'ap-northeast'),
       ('japaneast', 'ap-northeast'),
       ('brazilsouth', 'sa-east'),
       ('australiaeast', 'ap-southeast'),
       ('australiasoutheast', 'ap-southeast'),
       ('southindia', 'ap-southeast'),
       ('centralindia', 'ap-southeast'),
       ('westindia', 'ap-southeast'),
       ('canadacentral', 'us-central'),
       ('canadaeast', 'us-east'),
       ('uksouth', 'eu-west'),
       ('ukwest', 'eu-west'),
       ('westcentralus', 'us-central'),
       ('westus2', 'us-west'),
       ('koreacentral', 'ap-northeast'),
       ('koreasouth', 'ap-northeast'),
       ('francecentral', 'eu-south'),
       ('francesouth', 'eu-south'),
       ('us-east1', 'us-east'),
       ('us-east4', 'us-east'),
       ('us-central1', 'us-central'),
       ('us-west1', 'us-west'),
       ('northamerica-northeast1', 'us-east'),
       ('europe-west1', 'eu-west'),
       ('europe-west2', 'eu-west'),
       ('europe-west3', 'eu-central'),
       ('europe-west4', 'eu-central'),
       ('europe-west6', 'eu-east'),
       ('asia-east1', 'ap-northeast'),
       ('asia-east2', 'ap-northeast'),
       ('asia-northeast1', 'ap-northeast'),
       ('asia-southeast1', 'ap-southeast'),
       ('australia-southeast1', 'ap-southeast'),
       ('asia-south1', 'ap-southeast'),
       ('southamerica-east1', 'sa-east'),
       ('gcp-europe-west4', 'eu-east'),
       ('gcp-us-west2', 'us-west'),
       ('gcp-australia-southeast1', 'ap-southeast'),
       ('asia-southeast-1', 'ap-southeast'),
       ('asia-southeast-2', 'ap-southeast'),
       ('asia-southeast-3', 'ap-southeast');

-- INSERT INTO city
-- VALUES ('seattle', 'USD'),
--        ('san francisco', 'USD'),
--        ('los angeles', 'USD'),
--        ('phoenix', 'USD'),
--        ('minneapolis', 'USD'),
--        ('chicago', 'USD'),
--        ('detroit', 'USD'),
--        ('atlanta', 'USD'),
--        ('new york', 'USD'),
--        ('boston', 'USD'),
--        ('washington dc', 'USD'),
--        ('miami', 'USD'),
--        ('charlotte', 'USD'),
--        ('portland', 'USD'),
--        ('las vegas', 'USD'),
--        ('stockholm', 'SEK'),
--        ('helsinki', 'EUR'),
--        ('copenhagen', 'EUR'),
--        ('oslo', 'NOK'),
--        ('frankfurt', 'EUR'),
--        ('berlin', 'EUR'),
--        ('munich', 'EUR'),
--        ('hamburg', 'EUR'),
--        ('frankfurt', 'EUR'),
--        ('dusseldorf', 'EUR'),
--        ('leipzig', 'EUR'),
--        ('dortmund', 'EUR'),
--        ('essen', 'EUR'),
--        ('stuttgart', 'EUR'),
--        ('london', 'GBP'),
--        ('amsterdam', 'EUR'),
--        ('paris', 'EUR'),
--        ('manchester', 'GBP'),
--        ('liverpool', 'GBP'),
--        ('glasgow', 'GBP'),
--        ('birmingham', 'GBP'),
--        ('leeds', 'GBP'),
--        ('milano', 'EUR'),
--        ('madrid', 'EUR'),
--        ('athens', 'EUR'),
--        ('riga', 'EUR'),
--        ('tallinn', 'EUR'),
--        ('barcelona', 'EUR'),
--        ('dublin', 'EUR'),
--        ('belfast', 'EUR'),
--        ('amsterdam', 'EUR'),
--        ('rotterdam', 'EUR'),
--        ('brussels', 'EUR'),
--        ('ghent', 'EUR'),
--        ('antwerp', 'EUR'),
--        ('hague', 'EUR'),
--        ('amsterdam', 'EUR'),
--        ('singapore', 'SGD'),
--        ('hong kong', 'HKD'),
--        ('sydney', 'AUD'),
--        ('tokyo', 'JPY'),
--        ('sao paulo', 'BRL'),
--        ('rio de janeiro', 'BRL'),
--        ('salvador', 'BRL'),
--        ('madrid', 'EUR'),
--        ('barcelona', 'EUR'),
--        ('sintra', 'EUR'),
--        ('rome', 'EUR'),
--        ('milan', 'EUR'),
--        ('lyon', 'EUR'),
--        ('lisbon', 'EUR'),
--        ('toulouse', 'EUR'),
--        ('paris', 'EUR'),
--        ('cologne', 'EUR'),
--        ('seville', 'EUR'),
--        ('marseille', 'EUR'),
--        ('naples', 'EUR'),
--        ('turin', 'EUR'),
--        ('valencia', 'EUR'),
--        ('palermo', 'EUR'),
--        ('krakov', 'PLN'),
--        ('zagraeb', 'HRK'),
--        ('zaragoza', 'EUR'),
--        ('lodz', 'PLN'),
--        ('athens', 'EUR'),
--        ('bratislava', 'EUR'),
--        ('prague', 'CZK'),
--        ('sofia', 'BGN'),
--        ('bucharest', 'RON'),
--        ('vienna', 'EUR'),
--        ('warsaw', 'PLN'),
--        ('budapest', 'HUF')
-- ;