ALTER TABLE account PARTITION BY NOTHING;
ALTER TABLE transaction PARTITION BY NOTHING;
ALTER TABLE transaction_item PARTITION BY NOTHING;

ALTER TABLE account CONFIGURE ZONE DISCARD;
ALTER TABLE transaction CONFIGURE ZONE DISCARD;
ALTER TABLE transaction_item CONFIGURE ZONE DISCARD;
