spring:
  output:
    ansi:
      enabled: always
  shell:
    interactive:
      enabled: true
    version:
      enabled: true
      showBuildName: true
      showGitBranch: true
    history:
      name: client.history
logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) [%t] %clr([%logger{39}]){cyan} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
#############################
# Bank client config
#############################
roachbank:
  default-url: http://localhost:8090/api
  http:
    # Total concurrent http connections
    maxTotal: -1
    # Total concurrent http connections per route (endpoint)
    maxConnPerRoute: -1
