spring:
  jpa:
    properties:
      hibernate:
        dialect: io.roach.bank.repository.jpa.CockroachDBDialect
  flyway:
    enabled: true
    locations: classpath:db/crdb
  datasource:
    url: jdbc:cockroachdb://localhost:26257/roach_bank?sslmode=disable&retryTransientErrors=true&implicitSelectForUpdate=true
    driver-class-name: io.cockroachdb.jdbc.CockroachDriver
    username: root
    password:
roachbank:
  health:
    validation-query: select node_id from [SHOW CLUSTER SESSIONS] limit 1
