##############################################
# Spring boot properties
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
#
# See README.md for available Spring Profiles
##############################################

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: roach-bank
  profiles:
    active: retry-none,cdc-none,crdb-local
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
    deserialization:
      fail_on_unknown_properties: false
      fail_on_ignored_properties: false
    default-property-inclusion: non_null
    locale: en_US
  mvc:
    throw-exception-if-no-handler-found: true
  thymeleaf:
    cache: false
    mode: HTML
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0
          no-cache: true
          no-store: true
#############################
  jpa:
    show-sql: false
    open-in-view: false
  flyway:
    enabled: false
    connect-retries: 15
    clean-on-validation-error: true
    baseline-on-migrate: false
#    clean-disabled: true
  datasource:
    driver-class-name: io.cockroachdb.jdbc.CockroachDriver
    hikari:
      pool-name: roach-bank
      connection-init-sql: SELECT 1
      connection-timeout: 30000
      validation-timeout: 20000
      max-lifetime: 60000
      maximum-pool-size: 80
      minimum-idle: 80
#############################
logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr([%logger{39}]){cyan} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:%5p} [%t] %logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  file:
    name: .log/server.log
  logback:
    rollingpolicy:
      max-history: 3
#############################
info:
  build:
    artifact: io.roach.bank.server
    name: Roach Bank
    description: Accounting ledger based on Spring Boot and CockroachDB
    version: 1.0.0
    app-label: Roach Bank
#############################
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: env,info,health,metrics,flyway,prometheus
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
    db:
      enabled: false
  metrics:
    tags:
      application: ${spring.application.name}
#############################
# HTTP and HTTPS with self-signed cert for webhook sink
server:
  http:
    port: 8090
  port: 8443
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always
  ssl:
    key-store: classpath:cert/bank.p12
    key-store-password: secret
    key-store-type: pkcs12
    key-alias: bank
    key-password: secret
#############################
roachbank:
  health:
    # CRDB Admin UI endpoint base URL
    admin-endpoint: http://localhost:8080
    # Validation query for datasource health check
    validation-query: select 1
  # WS push permits per second rate limit
  pushPermitsPerSec: 4.0
  # Interval of pushing cached balance reports (millis) (default: 1h since its unused)
  reportPushInterval: 3600000
  # Report / WS push query timeout (seconds)
  pushTimeoutSeconds: 120
  # Default limit unless client specified
  accountsPerCityLimit: 100
  # Load account by reference or hit database with SELECT (former drastically reduce contention)
  loadAccountByReference: false
  # Account plan to run workload against
  accountPlan:
    # Clear accounts at startup
    clearAtStartup: true
    # Clear transactions transitively if clearAtStartup is true
    clearTransitive: true
    # Filter on region, empty implies all regions
    region: ""
    # Number of accounts per city (total: num_cities x numAccountsPerCity)
    numAccountsPerCity: 1000
    # Initial balance
    initialBalance: "25000.00"
    # Account currency
    currency: "USD"
