spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.CockroachDialect
  flyway:
    enabled: true
    locations: classpath:db/crdb
  datasource:
    url: jdbc:postgresql://kai-odin-gff.gcp-europe-west1.cockroachlabs.cloud:26257/roach_bank?sslmode=require
    driver-class-name: org.postgresql.Driver
    username: guest
    password: i7L0dVrbdpLvqkpI8dTRHA
roachbank:
  health:
    validation-query: select node_id from [SHOW CLUSTER SESSIONS] limit 1
