spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/psql
  datasource:
    url: jdbc:postgresql://localhost:5432/roach_bank
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
roachbank:
  health:
    validation-query: select 1
