spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.CockroachDialect
  flyway:
    enabled: true
    locations: classpath:db/crdb
  datasource:
    url: jdbc:postgresql://localhost:26257/roach_bank?sslmode=disable
    driver-class-name: org.postgresql.Driver
    username: root
roachbank:
  health:
    validation-query: select node_id from [SHOW CLUSTER SESSIONS] limit 1
