spring:
  datasource:
    url: jdbc:postgresql://192.168.1.99:5432/roach_bank
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    hikari:
      pool-name: roach-bank
      connection-init-sql: SELECT 1
      connection-timeout: 30000
      validation-timeout: 20000
      max-lifetime: 60000
      maximum-pool-size: 32
      minimum-idle: 32
roachbank:
  health:
    admin-endpoint: http://192.168.1.99:7070
  accountsPerCityLimit: 20
