spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.CockroachDialect
  flyway:
    enabled: true
    locations: classpath:db/crdb,classpath:db/common
  datasource:
    url: jdbc:postgresql://kai-odin-mzk.aws-eu-north-1.cockroachlabs.cloud:26257/roach_bank?sslmode=require
    username: guest
    password: kFRuMuctqZtnR7f_ksD4sQ
    driver-class-name: org.postgresql.Driver
