spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/psql,classpath:db/common
  datasource:
    url: jdbc:postgresql://localhost:5432/roach_bank
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED
