spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  flyway:
    enabled: true
    locations: classpath:db/migration/psql,classpath:db/migration/common
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://192.168.1.99:5432/roach_bank
    username: postgres
    password: root
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED
      driver-class-name: org.postgresql.Driver
roachbank:
  health:
    validation-query: select 1
    admin-endpoint: http://192.168.1.99:7070
