spring:
  datasource:
#    url: jdbc:postgresql://34.107.209.247:9092/roach_bank?sslmode=disable
    url: jdbc:postgresql://192.168.1.99:26300/roach_bank?sslmode=disable
    driver-class-name: org.postgresql.Driver
    username: root
    password: 
    hikari:
      pool-name: roach-bank
      connection-init-sql: SELECT 1
      connection-timeout: 30000
      validation-timeout: 20000
      max-lifetime: 60000
      maximum-pool-size: 32
      minimum-idle: 32
roachbank:
  health:
    admin-endpoint: http://192.168.1.99:7070
#  locality: europe_west4
  accountsPerRegionLimit: 10