spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  flyway:
    enabled: true
    locations: classpath:db/migration/psql,classpath:db/migration/common
  datasource:
    url: jdbc:postgresql://localhost:5432/roach_bank
    username: postgres
    password: root
    hikari:
      transaction-isolation: TRANSACTION_SERIALIZABLE
roachbank:
  health:
    validation-query: select 1
