spring:
  jpa:
    properties:
      hibernate:
        dialect: io.roach.bank.repository.jpa.CockroachDBDialect
  flyway:
    enabled: true
    locations: classpath:db/migration/crdb,classpath:db/migration/common
  datasource:
    url: jdbc:cockroachdb://192.168.1.99:26300/roach_bank?sslmode=disable
    driver-class-name: io.cockroachdb.jdbc.CockroachDriver
    username: root
roachbank:
  health:
    validation-query: select node_id from [SHOW CLUSTER SESSIONS] limit 1
    admin-endpoint: http://192.168.1.99:7070

