spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.CockroachDialect
  flyway:
    enabled: true
    locations: classpath:db/crdb,classpath:db/common
  datasource:
    url: jdbc:cockroachdb://kai-munin-1273.j77.aws-eu-central-1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full
    username: guest
    password: V4FvqDrHnBbKo7-Sx3wp3g
    driver-class-name: io.cockroachdb.jdbc.CockroachDriver
