spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.CockroachDialect
  flyway:
    enabled: true
    locations: classpath:db/crdb
  datasource:
    url: jdbc:postgresql://192.168.1.99:26257/roach_bank?sslmode=disable
    driver-class-name: org.postgresql.Driver
    username: root
