spring:
  jpa:
    properties:
      hibernate:
        dialect: io.roach.bank.repository.jpa.CockroachDBDialect
  flyway:
    enabled: true
    locations: classpath:db/migration/crdb,classpath:db/migration/common
  datasource:
    url: jdbc:postgresql://localhost:26257/roach_bank?sslmode=disable
    driver-class-name: org.postgresql.Driver
    username: root
    password:
#############################
roachbank:
  health:
    validation-query: select node_id from [SHOW CLUSTER SESSIONS] limit 1
